AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub OIDC Provider and IAM Role for GitHub Actions'

Parameters:
  GitHubOrg:
    Type: String
    Description: 'GitHub organization or username'
    Default: 'developmentseed'
  
  GitHubRepo:
    Type: String
    Description: 'GitHub repository name'
    Default: 's3-browser-upload'
  
  RoleName:
    Type: String
    Description: 'Name for the IAM role'
    Default: 'github-actions-role'

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrg}/${GitHubRepo}:*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Description: 'IAM role for GitHub Actions to deploy CDK stacks'
      MaxSessionDuration: 3600

Outputs:
  RoleArn:
    Description: 'ARN of the IAM role for GitHub Actions'
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  OIDCProviderArn:
    Description: 'ARN of the GitHub OIDC provider'
    Value: !Ref GitHubOIDCProvider
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn'
